path_classifiers:
  test:
    - test
extraction:
  python:
    python_setup:
      version: 3
      requirements_files:
        - requirements.txt
      setup_py: false
    index:
      exclude:
        - lib
        - lib3
        - lib2

queries:
  - exclude: py/import-and-import-from
