path_classifiers:
  test:
    - test
extraction:
  python:
    python_setup:
      version: 2
      requirements_files:
        # - requirements/requirements.txt
        - false
      setup_py: false
    index:
      exclude:
        - lib
        - lib3
        - lib2
